# Generated by Django 2.2.12 on 2021-01-08 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_type', models.SmallIntegerField(choices=[(0, '老师'), (1, '博士'), (2, '硕士'), (3, '本科生'), (4, '已毕业'), (5, '----')], default=5, null=True, verbose_name='用户类型')),
                ('stu_number', models.CharField(blank=True, default='---', max_length=16, verbose_name='学号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=web.models.user_directory_path, verbose_name='头像')),
                ('motto', models.CharField(blank=True, default='好好学习, 天天向上', max_length=64, verbose_name='签名')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'permissions': (('web__check_orders', '审核订单'), ('web__edit_history_orders', '修改历史订单'), ('web__edit_user_info', '修改用户信息')),
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='公司名称')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='DutyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sep_weeks', models.SmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '值日表',
                'verbose_name_plural': '值日表',
            },
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('brand', models.CharField(max_length=32, verbose_name='品牌/型号')),
                ('specification', models.CharField(blank=True, max_length=32, null=True, verbose_name='数量规格')),
                ('CAS_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='CAS号')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.SmallIntegerField(choices=[(0, '试剂购买'), (1, '基因测序'), (2, '引物合成')], default=0, verbose_name='订单类型')),
                ('gene_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='基因')),
                ('primer1', models.TextField(blank=True, null=True, verbose_name="引物序列1 (5'-3')")),
                ('primer2', models.TextField(blank=True, null=True, verbose_name="引物序列2 (5'-3')")),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价')),
                ('create_date', models.DateTimeField(verbose_name='创建日期')),
                ('checked_date', models.DateTimeField(blank=True, null=True, verbose_name='批准日期')),
                ('status', models.SmallIntegerField(choices=[(0, '未提交'), (1, '待审核'), (2, '审核未通过'), (3, '已批准')], verbose_name='订单状态')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('bill_received', models.BooleanField(default=False, verbose_name='收到底单')),
                ('review', models.CharField(blank=True, max_length=128, null=True, verbose_name='原因')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.CompanyInfo', verbose_name='公司')),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.GoodsDetail', verbose_name='商品')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_read', models.BooleanField(default=False)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField()),
                ('brief', models.CharField(max_length=32)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
        migrations.CreateModel(
            name='DutyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.DutyTable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '值日人',
                'verbose_name_plural': '值日人',
            },
        ),
    ]
