# Generated by Django 2.2.12 on 2020-12-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, '老师'), (1, '博士'), (2, '硕士'), (3, '本科生'), (4, '已毕业')], null=True, verbose_name='用户类型'),
        ),
    ]
