# Generated by Django 2.2.12 on 2020-12-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201217_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.GoodsDetail'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsdetail',
            unique_together={('name', 'brand')},
        ),
    ]
