# Generated by Django 2.2.12 on 2020-12-20 21:21

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201219_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('web__check_orders', '审核订单'), ('web__edit_history_orders', '修改历史订单'), ('web__edit_user_info', '修改用户信息'), ('web__watch_unchecked_order', '查看未审核订单')), 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.user_directory_path, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stu_number',
            field=models.CharField(blank=True, default='---', max_length=16, verbose_name='学号'),
        ),
    ]
