# Generated by Django 2.2.12 on 2020-12-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20201220_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('web__check_orders', '审核订单'), ('web__edit_history_orders', '修改历史订单'), ('web__edit_user_info', '修改用户信息')), 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, '老师'), (1, '博士'), (2, '硕士'), (3, '本科生'), (4, '已毕业'), (5, '----')], default=5, null=True, verbose_name='用户类型'),
        ),
    ]
